# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'questionWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_QuestionWindow(object):
    def setupUi(self, QuestionWindow):
        QuestionWindow.setObjectName("QuestionWindow")
        QuestionWindow.resize(629, 458)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("window.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        QuestionWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(QuestionWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 611, 381))
        self.widget.setObjectName("widget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(270, 400, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.pushButton.setFont(font)
        self.pushButton.setObjectName("pushButton")
        QuestionWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(QuestionWindow)
        self.statusbar.setObjectName("statusbar")
        QuestionWindow.setStatusBar(self.statusbar)

        self.retranslateUi(QuestionWindow)
        QtCore.QMetaObject.connectSlotsByName(QuestionWindow)

    def retranslateUi(self, QuestionWindow):
        _translate = QtCore.QCoreApplication.translate
        QuestionWindow.setWindowTitle(_translate("QuestionWindow", "Генератор тестов по программированию"))
        self.pushButton.setText(_translate("QuestionWindow", "Результат"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    QuestionWindow = QtWidgets.QMainWindow()
    ui = Ui_QuestionWindow()
    ui.setupUi(QuestionWindow)
    QuestionWindow.show()
    sys.exit(app.exec_())
